/**
 * vacancy ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Home } from './home';
import { Detail } from './detail';


export interface Config { 
    id?: number;
    name?: string | null;
    url?: string | null;
    pageSize?: number;
    pageSelector?: string | null;
    home?: Home;
    detail?: Detail;
}

