/**
 * vacancy ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyElement } from './myElement';


export interface Detail { 
    title?: MyElement;
    image?: MyElement;
    date?: MyElement;
    location?: MyElement;
    description?: MyElement;
    domain?: MyElement;
    company?: MyElement;
    fonction?: MyElement;
    educationLevel?: MyElement;
    salary?: MyElement;
    metadata?: Array<MyElement> | null;
}

