/**
 * vacancy ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MyElement } from './myElement';


export interface Job { 
    id?: number;
    title?: string | null;
    url?: string | null;
    image?: string | null;
    date?: string | null;
    location?: string | null;
    description?: string | null;
    domain?: string | null;
    company?: string | null;
    fonction?: string | null;
    educationLevel?: string | null;
    salary?: string | null;
    metadata?: Array<MyElement> | null;
}

