/**
 * vacancy ANCFCC
 * API documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: abdellah.elbekkali@digitransform.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Job } from './job';


export interface Submission { 
    jobId?: number;
    job?: Job;
    userId?: number;
    user?: User;
    date?: string;
    cv?: string | null;
}

